"""empty message

Revision ID: 143228012caa
Revises: e8c302433881
Create Date: 2021-12-03 03:05:37.594391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '143228012caa'
down_revision = 'e8c302433881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('item_name', sa.String(length=100), nullable=True))
    op.add_column('item', sa.Column('item_description', sa.String(length=100), nullable=True))
    op.drop_column('item', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('item', 'item_description')
    op.drop_column('item', 'item_name')
    # ### end Alembic commands ###
