"""empty message

Revision ID: 2b659afa8a50
Revises: 1cdcec912360
Create Date: 2021-11-30 00:53:42.770480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b659afa8a50'
down_revision = '1cdcec912360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bid', sa.Column('highest_bid', sa.Integer(), nullable=True))
    op.add_column('bid', sa.Column('num_of_bids', sa.String(length=250), nullable=True))
    op.drop_column('bid', 'starting_price')
    op.drop_column('bid', 'end_date')
    op.drop_column('bid', 'final_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bid', sa.Column('final_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bid', sa.Column('end_date', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('bid', sa.Column('starting_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('bid', 'num_of_bids')
    op.drop_column('bid', 'highest_bid')
    # ### end Alembic commands ###
