"""empty message

Revision ID: 5c846fda90b1
Revises: c4113b8331b7
Create Date: 2021-11-30 04:28:46.199697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c846fda90b1'
down_revision = 'c4113b8331b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'name')
    # ### end Alembic commands ###
