"""empty message

Revision ID: c4113b8331b7
Revises: 2b659afa8a50
Create Date: 2021-11-30 01:24:26.515680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4113b8331b7'
down_revision = '2b659afa8a50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bid', sa.Column('bid_amount', sa.Integer(), nullable=True))
    op.add_column('bid', sa.Column('current_price', sa.Integer(), nullable=True))
    op.drop_column('bid', 'highest_bid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bid', sa.Column('highest_bid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('bid', 'current_price')
    op.drop_column('bid', 'bid_amount')
    # ### end Alembic commands ###
